# Generated by Django 6.1.1 on 2026-09-12 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2026-2027', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('room_type', models.CharField(choices=[('lecture', 'Standard Classroom / Homeroom'), ('science_lab', 'Science Laboratory'), ('computer_lab', 'Computer Laboratory'), ('tvl_workshop', 'TVL / TLE Workshop'), ('gym', 'Gymnasium / Open Court')], default='lecture', max_length=30)),
                ('capacity', models.IntegerField(default=45)),
                ('building', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade_level', models.IntegerField(choices=[(7, 'Grade 7 (JHS)'), (8, 'Grade 8 (JHS)'), (9, 'Grade 9 (JHS)'), (10, 'Grade 10 (JHS)'), (11, 'Grade 11 (SHS)'), (12, 'Grade 12 (SHS)')])),
                ('cluster', models.CharField(choices=[('jhs_core', 'JHS MATATAG Curriculum Core'), ('shs_core', 'SSHS Core Subject'), ('shs_stem', 'SSHS Academic - STEM Cluster'), ('shs_arts_ssh', 'SSHS Academic - Arts, Social Sciences & Humanities'), ('shs_sports_health', 'SSHS Academic - Sports, Health & Wellness'), ('shs_tech_pro', 'SSHS Tech-Pro (TVL) Elective')], default='jhs_core', max_length=30)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='scheduler.academicyear')),
                ('homeroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_sections', to='scheduler.room')),
            ],
            options={
                'unique_together': {('name', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('grade_level', models.IntegerField(choices=[(7, 'Grade 7 (JHS)'), (8, 'Grade 8 (JHS)'), (9, 'Grade 9 (JHS)'), (10, 'Grade 10 (JHS)'), (11, 'Grade 11 (SHS)'), (12, 'Grade 12 (SHS)')])),
                ('cluster', models.CharField(choices=[('jhs_core', 'JHS MATATAG Curriculum Core'), ('shs_core', 'SSHS Core Subject'), ('shs_stem', 'SSHS Academic - STEM Cluster'), ('shs_arts_ssh', 'SSHS Academic - Arts, Social Sciences & Humanities'), ('shs_sports_health', 'SSHS Academic - Sports, Health & Wellness'), ('shs_tech_pro', 'SSHS Tech-Pro (TVL) Elective')], default='jhs_core', max_length=30)),
                ('room_type_needed', models.CharField(choices=[('lecture', 'Standard Classroom / Homeroom'), ('science_lab', 'Science Laboratory'), ('computer_lab', 'Computer Laboratory'), ('tvl_workshop', 'TVL / TLE Workshop'), ('gym', 'Gymnasium / Open Court')], default='lecture', max_length=30)),
                ('weekly_periods', models.IntegerField(default=4, help_text='Number of 1-hour periods per week')),
                ('consecutive_periods', models.IntegerField(default=1, help_text='1 for standard, 2 for double-period lab/workshop')),
                ('is_lab', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='scheduler.department')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('max_daily_hours', models.IntegerField(default=6, help_text='DepEd DO 005 s. 2024 (max 6h actual teaching)')),
                ('max_weekly_hours', models.IntegerField(default=30)),
                ('preferred_vacant_period', models.IntegerField(blank=True, help_text='Preferred vacant period (1-8)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='scheduler.department')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('term_type', models.CharField(choices=[('jhs_full_year', 'JHS - Full School Year (4 Quarters)'), ('shs_term_1', 'SSHS - Term 1 (Trimester)'), ('shs_term_2', 'SSHS - Term 2 (Trimester)'), ('shs_term_3', 'SSHS - Term 3 (Trimester)')], default='shs_term_1', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='scheduler.academicyear')),
            ],
            options={
                'unique_together': {('academic_year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft (Editing / Work-in-Progress)'), ('published', 'Official Published Timetable'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('fitness_score', models.FloatField(default=0.0)),
                ('hard_conflicts_count', models.IntegerField(default=0)),
                ('soft_conflicts_count', models.IntegerField(default=0)),
                ('generation_iterations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduler.academicyear')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduler.term')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')])),
                ('period_number', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('label', models.CharField(max_length=50)),
                ('is_break', models.BooleanField(default=False, help_text='Flag Ceremony, Recess, or Lunch Break')),
            ],
            options={
                'ordering': ['day_of_week', 'period_number'],
                'unique_together': {('day_of_week', 'period_number')},
            },
        ),
        migrations.CreateModel(
            name='SectionSubjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_requirements', to='scheduler.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_requirements', to='scheduler.subject')),
                ('assigned_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.teacher')),
            ],
            options={
                'unique_together': {('section', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TeacherQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualified_teachers', to='scheduler.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='scheduler.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False, help_text='Preserve manual swap during re-generation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='scheduler.room')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scheduler.schedule')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='scheduler.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='scheduler.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='scheduler.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='scheduler.timeslot')),
            ],
            options={
                'unique_together': {('schedule', 'section', 'time_slot')},
            },
        ),
    ]
