# Generated by Django 6.1.1 on 2026-09-12 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='curriculum_level',
            field=models.CharField(choices=[('jhs', 'Junior High School (Grades 7–10)'), ('shs', 'Senior High School (Grades 11–12)'), ('both', 'Both JHS & SHS (Integrated)')], default='both', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='scheduler.department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='scheduler.department'),
        ),
    ]
