# Generated by Django 6.1.1 on 2026-09-12 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_teacher_curriculum_level_alter_subject_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_sections', to='scheduler.teacher'),
        ),
        migrations.CreateModel(
            name='AncillaryDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Designation or Ancillary Title', max_length=150)),
                ('designation_type', models.CharField(choices=[('adviser', 'Class Advisory (Adviser)'), ('ict_coordinator', 'School ICT / LIS Coordinator'), ('drrm_coordinator', 'Disaster Risk Reduction (DRRM) Coordinator'), ('school_paper', 'School Paper / Campus Journalism Adviser'), ('scout_coordinator', 'BSP / GSP Scout Coordinator'), ('dept_coordinator', 'Department / Grade Level Coordinator'), ('guidance_designate', 'Guidance Counselor Designate'), ('canteen_manager', 'Canteen / Feeding Program Manager'), ('property_custodian', 'Property Custodian / Supply Designate'), ('sports_coach', 'Sports / Athletic Club Coach'), ('reading_coordinator', 'Reading / Remediation Coordinator'), ('custom', 'Other Special Designation')], default='custom', max_length=50)),
                ('weekly_hours', models.FloatField(default=2.0, help_text='Credited hours/week under DepEd DO 005 s. 2024')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancillary_duties', to='scheduler.teacher')),
            ],
        ),
    ]
