# Generated by Django 6.1.1 on 2026-09-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_section_adviser_ancillaryduty'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='ISABELA NATIONAL HIGH SCHOOL', max_length=200)),
                ('school_id', models.CharField(blank=True, default='300582', max_length=50)),
                ('region', models.CharField(default='REGION II – CAGAYAN VALLEY', max_length=150)),
                ('division', models.CharField(default='SCHOOLS DIVISION OF ISABELA', max_length=150)),
                ('district', models.CharField(blank=True, default='District II', max_length=100)),
                ('prepared_by_name', models.CharField(default='VILMA L. VILLADOR, PhD', max_length=150)),
                ('prepared_by_title', models.CharField(default='Principal II', max_length=150)),
                ('reviewed_by_name', models.CharField(default='JOVITO M. CADIZ, PhD', max_length=150)),
                ('reviewed_by_title', models.CharField(default='Principal IV, District-in-Charge', max_length=150)),
                ('verified_by_name', models.CharField(default='MARIETESS B. BAQUIRAN, PhD', max_length=150)),
                ('verified_by_title', models.CharField(default='Chief, Curriculum Instruction Division', max_length=150)),
                ('recommending_name', models.CharField(default='MARY JULIE A. TRUS, PhD, CESO VI', max_length=150)),
                ('recommending_title', models.CharField(default='Assistant Schools Division Superintendent', max_length=150)),
                ('approved_by_name', models.CharField(default='RACHEL R. LLANA, PhD, CESO V', max_length=150)),
                ('approved_by_title', models.CharField(default='Schools Division Superintendent', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['grade_level', 'day_of_week', 'period_number']},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='grade_level',
            field=models.IntegerField(choices=[(0, 'All / Universal'), (7, 'Grade 7 (JHS)'), (8, 'Grade 8 (JHS)'), (9, 'Grade 9 (JHS)'), (10, 'Grade 10 (JHS)'), (11, 'Grade 11 (SHS)'), (12, 'Grade 12 (SHS)')], default=0, help_text='Grade level this timeframe applies to (0 for Universal)'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('day_of_week', 'period_number', 'grade_level')},
        ),
    ]
