# Generated by Django 6.1.1 on 2026-09-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_schoolprofile_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. pure_academic, stem, humss, jhs_core', max_length=50, unique=True)),
                ('name', models.CharField(help_text='e.g. Pure Academic, STEM Cluster, Humanities', max_length=150)),
                ('curriculum_level', models.CharField(choices=[('jhs', 'Junior High School (JHS)'), ('shs', 'Senior High School (SHS)'), ('both', 'Both JHS & SHS')], default='shs', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='cluster',
            field=models.CharField(default='jhs_core', max_length=60),
        ),
        migrations.AlterField(
            model_name='subject',
            name='cluster',
            field=models.CharField(default='jhs_core', max_length=60),
        ),
    ]
