# Generated by Django 6.1.1 on 2026-09-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_curriculumcluster_alter_section_cluster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AncillaryDesignationCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. ict_coordinator, property_custodian', max_length=50, unique=True)),
                ('name', models.CharField(help_text='e.g. School ICT / LIS Coordinator', max_length=150)),
                ('default_weekly_hours', models.FloatField(default=2.0)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. lecture, science_lab, speech_lab, avr', max_length=50, unique=True)),
                ('name', models.CharField(help_text='e.g. Standard Classroom, Science Laboratory', max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='active_academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.academicyear'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='active_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.term'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='max_daily_teaching_hours',
            field=models.IntegerField(default=6, help_text='Max actual classroom teaching hours per day'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='max_weekly_teaching_hours',
            field=models.IntegerField(default=30, help_text='Max actual classroom teaching hours per week'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='standard_workweek_hours',
            field=models.IntegerField(default=40, help_text='Total official weekly work hours'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='lecture', max_length=60),
        ),
        migrations.AlterField(
            model_name='subject',
            name='room_type_needed',
            field=models.CharField(default='lecture', max_length=60),
        ),
    ]
