# Generated by Django 6.1.1 on 2026-09-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_ancillarydesignationcatalog_facilitytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='max_daily_teaching_hours',
            field=models.FloatField(default=6.0, help_text='Max actual classroom teaching hours per day'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='max_weekly_teaching_hours',
            field=models.FloatField(default=30.0, help_text='Max actual classroom teaching hours per week'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='standard_workweek_hours',
            field=models.FloatField(default=40.0, help_text='Total official weekly work hours'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='weekly_periods',
            field=models.FloatField(default=4.0, help_text='Number of 1-hour periods per week (supports decimals like 1.5, 4.5)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_daily_hours',
            field=models.FloatField(default=6.0, help_text='DepEd DO 005 s. 2024 (max 6h actual teaching)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='max_weekly_hours',
            field=models.FloatField(default=30.0),
        ),
    ]
